-- MySQL Script generated by MySQL Workbench
-- Thu May  9 09:55:40 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema users_datas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema users_datas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `users_datas` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `users_datas` ;

-- -----------------------------------------------------
-- Table `users_datas`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users_datas`.`users` ;

CREATE TABLE IF NOT EXISTS `users_datas`.`users` (
  `iduser` SERIAL UNIQUE,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `group` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users_datas`.`orthoPatient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users_datas`.`orthoPatient` ;

CREATE TABLE IF NOT EXISTS `users_datas`.`orthoPatient` (
  `idorthoPatient` SERIAL UNIQUE,
  `FK_IDOrtho` INT NOT NULL,
  `FK_IDPatient` INT NOT NULL,
  PRIMARY KEY (`idorthoPatient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users_datas`.`notes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users_datas`.`notes` ;

CREATE TABLE IF NOT EXISTS `users_datas`.`notes` (
  `idnote` SERIAL UNIQUE,
  `FK_IDOrtho` INT NOT NULL,
  `FK_IDPatient` INT NOT NULL,
  `note` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`idnote`))
ENGINE = InnoDB;

