-- MySQL Script generated by MySQL Workbench
-- Mon May  6 21:00:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema users_datas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema users_datas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `users_datas` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `users_datas` ;

-- -----------------------------------------------------
-- Table `users_datas`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users_datas`.`users` ;

CREATE TABLE IF NOT EXISTS `users_datas`.`users` (
  `iduser`  SERIAL UNIQUE,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `group` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users_datas`.`orthoPatient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users_datas`.`orthoPatient` ;

CREATE TABLE IF NOT EXISTS `users_datas`.`orthoPatient` (
  `idorthoPatient` SERIAL UNIQUE,
  `FK_IDOrtho` INT NOT NULL,
  `FK_IDPatient` INT NOT NULL,
  PRIMARY KEY (`idorthoPatient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `users_datas`.`notes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `users_datas`.`notes` ;

CREATE TABLE IF NOT EXISTS `users_datas`.`notes` (
  `idnote` SERIAL UNIQUE,
  `IDOrtho` INT NOT NULL,
  `IDPatient` INT NOT NULL,
  `note` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`idnote`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
